### **Problem Statement 1**

Write a NumPy program to multiply a MxN matrix by a NxA matrix and create a real matrix product.

Example: 

    Input: 5  3  2

    Output: First array:
                [[0.94293584 0.8091474  0.72330868]
                 [0.91143684 0.54976631 0.37547562]
                 [0.3656866  0.94185543 0.98414967]
                 [0.81470666 0.80629404 0.46326721]
                 [0.40648925 0.70615124 0.4786933 ]]
            Second array:
                [[0.45507569 0.53265048]
                 [0.41761748 0.87547934]
                 [0.83832095 0.79087463]]
            Dot product of two arrays:
                [[1.37338609 1.78269354]
                 [0.95913385 1.26374046]
                 [1.38478366 1.79769712]
                 [1.09584228 1.50623395]
                 [0.8811831  1.21332391]]

In [ ]:
import numpy as np
m=int(input("Enter value M: "))
n=int(input("Enter value N: "))
a=int(input("Enter value A: "))
x = np.random.random((m,n))
print("First array:")
print(x)
y = np.random.random((n,a))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

Enter value M: 5
Enter value N: 3
Enter value A: 2
First array:
[[0.91614484 0.45545931 0.17279562]
 [0.20634906 0.35813794 0.81266181]
 [0.98721037 0.82108427 0.02670186]
 [0.04485951 0.46053448 0.08879493]
 [0.04227533 0.54767138 0.29793239]]
Second array:
[[0.22269915 0.71883648]
 [0.23902122 0.55888353]
 [0.92288975 0.86503086]]
Dot product of two arrays:
[[0.47236042 1.06258058]
 [0.88155358 1.05146617]
 [0.44075035 1.19163124]
 [0.20201562 0.36644214]
 [0.41527852 0.59419428]]


### **Problem Statement 2**

Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

Hint: You can use isdigit(),islower(), and isupper() function.

Example: 

    Input: Original Array:
           ['Python' 'PHP' 'JS' 'Examples' 'html5' '5']

    Output: Digits only = [False False False False False  True]
            Lower cases only = [False False False False  True False]
            Upper cases only = [False  True  True False False False

In [ ]:
import numpy as np
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=str)
print("\nOriginal Array:")
print(x,"\n")
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)


Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5'] 

Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


### **Problem Statement 3**

Write a program which reads two space-separated positive integers X and Y as input and perform the following tasks:

#### **Tasks to be performed:**

1. Create a list (lst1) starting at one (1) with 16 elements at a step of X
2. Create a list (lst2) starting at one (1) with 16 elements at a step of Y
3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4. Reshape both the NumPy arrays to (4,4)
5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 - np2)
6. Print all the elements of np3 in a single dimension list like format as shown below:
              [n0 n1 n2 n3 n4 n5 n6 n7 n8]

Example:

Input: 7 9 

Output: [  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]

In [ ]:
import numpy as np
X,Y=map(int,input().split(' '))

lst1=list(range(1,X*16,X))
lst2=list(range(1,Y*16,Y))
np1=np.array(lst1)
np2=np.array(lst2)
np1=np1.reshape((4,4))
np2=np2.reshape((4,4))
np3=np.ravel(np1-np2)
print(np3)


7 9
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


### **Problem Statement 4**

Write a Python program which takes two integer-NumPy arrays, P and Q of shape [3 * 3] and perform the following task:

Task to be performed:
Print the element-wise difference of the matrix P and Q (P-Q).

Topics covered:
Append function
Matrix subtraction
Example:

Input: 

23 56 87 3 6 96 4 6 78

12 34 54 7 2 54 6 2 78

Output: [[11 22 33]
         [-4  4 42]
         [-2  4  0]]

In [ ]:
import numpy as np

arr1 = list()
arr2 = list()
arr1.append(input().split(' '))
arr2.append(input().split(' '))

array_1 = np.array(arr1, int).reshape(3,3)
array_2 = np.array(arr2, int).reshape(3,3)

print(array_1 - array_2)

23 56 87 3 6 96 4 6 78
12 34 54 7 2 54 6 2 78
[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
