In [ ]:
#Problem Statement1: Write a Python program to multiply a M X N matrix by N X A matrix and create a real matrix product.

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],
                [1,2,3],
                [1,2,3],
                [1,2,3],
                [1,2,3]])
arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
arr2 = np.array([[1,2],
                 [1,2],
                 [1,2]])
arr2

array([[1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
dot_product = np.dot(arr1, arr2)
print("Dot product of Two Array:",dot_product)

Dot product of Two Array: [[ 6 12]
 [ 6 12]
 [ 6 12]
 [ 6 12]
 [ 6 12]]


In [ ]:
#Problem Statement2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

In [ ]:
import numpy as np
original_array = np.array(['Python', 'PHP', 'JS', 'Examples','html5', '5'])

print("Original Array:",original_array)
check_digit = np.char.isdigit(original_array)
print("Digits only:",check_digit)

lower_case = np.char.islower(original_array)
print("Lower case only:",lower_case)

upper_case = np.char.isupper(original_array)
print("Upper case only:",upper_case)



Original Array: ['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only: [False False False False False  True]
Lower case only: [False False False False  True False]
Upper case only: [False  True  True False False False]


In [ ]:
#Problem Statement 3: Write a program that reads two space-separated positive integers X and Y as input and perform the following tasks:
import numpy as np
x,y = input('Enter values of X and Y: ').split('  ')
x = int(x)
y = int(y)

lst1 = list(range(1,500,x)[:16])
lst2 = list(range(1,500,y)[:16])

#Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
np1 = np.array(lst1)
np2 = np.array(lst2)

#Reshape both the NumPy arrays to (4,4)
np1 = np1.reshape(4,4)
np2 = np2.reshape(4,4)

#Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)
np3 = np1 - np2

#Print all the elements of np3 in a single dimension list
np3 = np3.ravel()
print(np3)

Enter values of X and Y: 7  9
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


In [ ]:

# Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of shape [3 ∗ 3]

import numpy as np
p = np.array([[23, 56, 87],
              [3, 6, 96],
              [4, 6, 78]])
print("Matrix P:", p)

q = np.array([[12, 34, 54],
              [7, 2, 54],
              [6, 2, 78]])
print("Matrix Q:", q)
res = []
for sub1, sub2 in zip(p, q):
    temp = []

    # iterate for elements
    for ele1, ele2 in zip(sub1, sub2):
        temp.append(ele1 - ele2)
    res.append(temp)
print("The Matrix Difference : " + str(res))



Matrix P: [[23 56 87]
 [ 3  6 96]
 [ 4  6 78]]
Matrix Q: [[12 34 54]
 [ 7  2 54]
 [ 6  2 78]]
The Matrix Difference : [[11, 22, 33], [-4, 4, 42], [-2, 4, 0]]
